CREATE TABLE IF NOT EXISTS `zombie_zones` (
    `id` VARCHAR(50) NOT NULL PRIMARY KEY,
    `name` VARCHAR(100) NOT NULL,
    `coords` LONGTEXT NOT NULL,
    `radius` FLOAT NOT NULL DEFAULT 150.0,
    `active` TINYINT(1) NOT NULL DEFAULT 1,
    `zombieMax` INT NOT NULL DEFAULT 20,
    `zombieHealth` INT NOT NULL DEFAULT 150,
    `zombieSpeed` FLOAT NOT NULL DEFAULT 1.2,
    `zombieDamage` INT NOT NULL DEFAULT 15,
    `weather` VARCHAR(50) NOT NULL DEFAULT 'HALLOWEEN',
    `halloween` TINYINT(1) NOT NULL DEFAULT 0,
    `blip` LONGTEXT DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `zombie_vehicles` (
    `id` VARCHAR(50) NOT NULL PRIMARY KEY,
    `model` VARCHAR(50) NOT NULL,
    `coords` LONGTEXT NOT NULL,
    `heading` FLOAT NOT NULL DEFAULT 0.0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `zombie_props` (
    `id` VARCHAR(50) NOT NULL PRIMARY KEY,
    `model` VARCHAR(50) NOT NULL,
    `coords` LONGTEXT NOT NULL,
    `heading` FLOAT NOT NULL DEFAULT 0.0,
    `owner` VARCHAR(100) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `zombie_player_infection` (
    `identifier` VARCHAR(100) NOT NULL PRIMARY KEY,
    `infection` INT NOT NULL DEFAULT 0,
    `stage` INT NOT NULL DEFAULT 0,
    `transformed` TINYINT(1) NOT NULL DEFAULT 0,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
